package io.kestra.plugin.anthropic;

import com.anthropic.client.okhttp.AnthropicOkHttpClient;
import com.anthropic.models.messages.MessageCreateParams;
import com.anthropic.models.messages.MessageParam;
import com.anthropic.models.messages.Model;
import io.kestra.core.models.annotations.Example;
import io.kestra.core.models.annotations.Plugin;
import io.kestra.core.models.property.Property;
import io.kestra.core.models.tasks.RunnableTask;
import io.kestra.core.runners.RunContext;
import io.kestra.core.serializers.JacksonMapper;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotEmpty;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

import java.util.List;

@SuperBuilder
@ToString
@EqualsAndHashCode
@Getter
@NoArgsConstructor
@Schema(
    title = "Complete a chat using the Anthropic Claude API.",
    description = "Send messages to Claude models and receive responses. Refer to the [Anthropic Console Settings](https://console.anthropic.com/settings/keys) to create an API key and the [Anthropic API documentation](https://docs.anthropic.com/claude/reference/messages_post) for more information."
)
@Plugin(
    examples = {
        @Example(
            title = "Chat completion using Claude.",
            full = true,
            code = """
                id: anthropic_chat_completion
                namespace: company.team

                tasks:
                  - id: chat_completion
                    type: io.kestra.plugin.anthropic.ChatCompletion
                    apiKey: "{{ secret('ANTHROPIC_API_KEY') }}"
                    model: "claude-3-5-sonnet-20241022"
                    maxTokens: 1024
                    messages:
                      - type: USER
                      - content: "What is the capital of Japan? Answer with a unique word and without any punctuation."
                """
        )
    }
)
public class ChatCompletion extends AbstractAnthropic implements RunnableTask<ChatCompletion.Output> {

    @Schema(title = "Messages", description = "List of messages to send to Claude")
    @NotEmpty
    private Property<List<ChatMessage>> messages;

    @Override
    public Output run(RunContext runContext) throws Exception {
        var renderedApiKey = runContext.render(apiKey).as(String.class).orElseThrow();
        var renderedModel = runContext.render(model).as(String.class).orElseThrow();
        var renderedMaxTokens = runContext.render(maxTokens).as(Long.class).orElse(1024L);
        var renderedMessages = runContext.render(messages).asList(ChatMessage.class);
        var renderedTemperature = runContext.render(temperature).as(Double.class).orElse(1.0);
        var renderedTopP = runContext.render(topP).as(Double.class);
        var renderedTopK = runContext.render(topK).as(Integer.class);

        var client = AnthropicOkHttpClient.builder()
            .apiKey(renderedApiKey)
            .build();

        List<MessageParam> messageParams = renderedMessages.stream()
            .map(message -> MessageParam.builder()
                .role(MessageParam.Role.of(message.type.role()))
                .content(message.content)
                .build())
            .toList();

        var paramsBuilder = MessageCreateParams.builder()
            .model(Model.of(renderedModel))
            .maxTokens(renderedMaxTokens)
            .temperature(renderedTemperature);

        renderedTopP.ifPresent(paramsBuilder::topP);
        renderedTopK.ifPresent(paramsBuilder::topK);

        paramsBuilder.messages(messageParams);

        var params = paramsBuilder.build();
        var response = client.messages().create(params);

        sendMetrics(runContext, response);

        return Output.builder()
            .rawResponse(JacksonMapper.ofJson().writeValueAsString(response))
            .outputText(response.content().toString())
            .build();
    }

    @Builder
    public record ChatMessage(ChatMessageType type, String content) {
    }

    public enum ChatMessageType {
        SYSTEM("system"),
        AI("assistant"),
        USER("user");

        private final String role;

        ChatMessageType(String role) {
            this.role = role;
        }

        public String role() {
            return role;
        }
    }

    @Builder
    @Getter
    public static class Output implements io.kestra.core.models.tasks.Output {
        @Schema(title = "The full response from Claude.")
        private String rawResponse;

        @Schema(title = "The content generated by Claude.")
        private String outputText;
    }
}